const { width: screenWidth } = Dimensions.get('window');
import {Dimensions} from "react-native";

//#2D9CFF
//#4CD964
export default function getStyles(mode){
    return{
    container: {
      width: screenWidth-32,
      height: screenWidth + 5,
      backgroundColor: "white",
      borderRadius: 20,
      paddingTop: 7,
      paddingBottom: 10,
      paddingLeft: 10,
      paddingRight: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 4,
      borderWidth: 1.3,
      borderColor: 'black',
      borderBottomWidth: 6,
      borderBottomColor: 'black',
      borderBottomLeftRadius: 24,
      borderBottomRightRadius: 24
    },
    innerContainer: {
      overflow: "hidden",
      //height: 230,
    },
    graphHeaderContainer: {
      width: '90%',    // or a fixed width like 300
      alignSelf: 'center',
    },
    graphHeaderText:{
      textAlign:"center",
      fontSize:20,
      fontWeight:'bold',
      marginBottom:10
    },
    helpButton: {
      position: "absolute",
      top: 0,
      right: 4,
      zIndex: 1,
    },
    insightButton: {
      position: "absolute",
      top: 40,
      right: 1,
      zIndex: 1,
    },
    changeSelected:{
      backgroundColor: mode === true ? "#2D9CFF" : '#4CD964',
      borderWidth: 2,
      borderRadius: 10,
      borderColor: mode === true? "blue":"green",
      padding: 10,
      alignItems: "center",
      justifyContent: "space-between",
      marginTop:5,
    },
    changeSelectedText: {
      fontSize: 16,
      fontWeight: "bold",
      color: "white",
      flexShrink: 1,
      fontFamily: 'Inter_600SemiBold',
    },
    dataSelector: {
      justifyContent: "center",
      alignItems: "center",
      flexDirection: "row",
      marginTop: 0,

    },
    dataSelectorButton: {
      backgroundColor: mode === true ? "#2D9CFF" : '#4CD964',
      height: 40,
      width: "30%",
      borderRadius: 10,
      alignSelf: "center",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      marginTop: 0,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 4,
      borderWidth: 1.2,
      borderColor: 'black',
      borderBottomWidth: 3,
      borderBottomColor: 'black',
      borderBottomLeftRadius: 11,
      borderBottomRightRadius: 11,
    },
    dataSelectorButtonClicked: {
      backgroundColor: mode === true? "#00538f":"green",
      height: 40*1.05,
      width: "30%",
      borderRadius: 10,
      alignSelf: "center",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      marginTop: 0,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 4,
      borderWidth: 1.2*1.05,
      borderColor: 'black',
      borderBottomWidth: 4,
      borderBottomColor: 'black',
      borderBottomLeftRadius: 11,
      borderBottomRightRadius: 11,
    },
    dataSelectorText:{
      color:'white',
      fontSize:14
    },
    metricSelectorContainer: {
      flexDirection: 'row',
      marginTop: 5,
      marginBottom: 20,
      gap: 10,
    },
    metricSelectorButton: {
      flex: 1,
      backgroundColor: mode === true ? "#2D9CFF" : '#4CD964',
      padding: 10,
      borderRadius: 10,
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 4,
      borderWidth: 1.2,
      borderColor: 'black',
      borderBottomWidth: 3,
      borderBottomColor: 'black',
      borderBottomLeftRadius: 11,
      borderBottomRightRadius: 11,
    },
    metricSelectorButtonSelected: {
      flex: 1,
      backgroundColor: mode === true? "#00538f":"#277C3C", //#399650
      padding: 10,
      borderRadius: 10,
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 4,
      borderWidth: 1.2*1.05,
      borderColor: 'black',
      borderBottomWidth: 4,
      borderBottomColor: 'black',
      borderBottomLeftRadius: 11,
      borderBottomRightRadius: 11,
    },
    metricSelectorText: {
      fontSize: 16,
      fontWeight: '600',
      color: "white",
      fontFamily: 'Inter_600SemiBold',
    },
    metricSelectorTextSelected: {
      fontSize: 16,
      fontWeight: '600',
      color: "white",
      fontFamily: 'Inter_600SemiBold'
    }
      }
  }